### ISSUE TITLE
Implement ability to look up objects uniquely by set query

### ISSUE THREAD

**Issue by jathanism** [dropbox/pynsot#119]
Now that https://github.com/dropbox/nsot/pull/228 is live... We need to port this to the CLI.

**Comment by jathanism** [comment]
I took a stab at this and I think it's going to be more difficult than initially anticipated.

Not terribly difficult, mind you. But it's not just gonna be drop-in because the `/api/networks/:id/query/` path is distinct just like other similiar "sub-commands" like "children" (`/api/networks/:id/children/` and it's making me wonder if we shouldn't rethink the way that set queries are performed from the CLI a little bit.

**Comment by nickpegg** [comment]
Fixed by #133
