### ISSUE TITLE
List supernets via CIDR

### ISSUE THREAD

**Issue by coxley** [dropbox/pynsot#47]
Would it fit into the flow of things to be able to list out a prefixes children via the cidr instead of only the ID? My thought being that you'd most likely have to do `nsot networks list -c 10.1.0.0/16` to find the ID anyway to then rerun with `-i 4 subnets` or something.

If so, I'd be more than happy to submit a PR for maybe autolooking up the ID via the prefix for the user in the background.

**Comment by gmjosack** [comment]
:+1: 

In general I feel like requiring users to use id's feels like a frustrating user experience. When we have unique columns we should allow using that as well (Device -> hostname, Network -> cidr, etc)

**Comment by jathanism** [comment]
I also agree. We already have a way to lookup objects by unique identifier in list view e.g. `nsot devices list -H foo-bar1`). This shouldn't too be hard!

**Comment by coxley** [comment]
You're on a roll!!
