### ISSUE TITLE
NsoT allows custom AUTH_HEADER, but pynsot doesn't

### ISSUE THREAD

**Issue by coxley** [dropbox/pynsot#57]
This is hardcoded in `client.py` as a global `AUTH_HEADER = 'X-NSoT-Email'`.

Should be able to fetch this from config. Currently breaks using pynsot at all with the unablitity to fetch `/api/authenticate`

**Comment by coxley** [comment]
Perhaps this is supported in some way, but is not supported if server uses non-default header and client wishes to do `auth_token`

**Comment by jathanism** [comment]
The default is hard-coded, but it's configurable both in your `.pynsotrc` file if `auth_method=auth_header`, or passable as an argument to the client constructor (`auth_header='X-Foo'`). This, however, probably isn't documented properly.

**Comment by coxley** [comment]
This issue is foobar, my problem was accidental where one vhost was setting my `auth_header` as empty string when proxying to the backend.
