### ISSUE TITLE
Make updating a single object easier from the CLI

### ISSUE THREAD

**Issue by jathanism** [dropbox/pynsot#66]
Right now you have to perform two steps: 1. Lookup the object by natural key (e.g. hostname) to retrieve the ID, 2. Use the ID to update the object.

If there's only a single object (since natural keys are unique anyhow), we should allow updating the object by the natural key. Unless... That is, you're trying to update the natural key. Heh.

**Comment by coxley** [comment]
Is this supported in the upstream API or will this feature in pynsot be more of an abstraction to the lookup -> use id?

**Comment by jathanism** [comment]
The latter. There was already some machinery put into the CLI app to make this easier to lookup subnets/supernets for Networks by cidr instead of having to always do it by ID. 

See: https://github.com/dropbox/pynsot/commit/0f45b173cbf3f742eb10b8e4a340d6813bbc860b#diff-ca243ed98917e3b00bbfa99da9a4e123R197
