### ISSUE TITLE
Improve grep-friendlieness of CLI output when displaying lists of objects

### ISSUE THREAD

**Issue by jathanism** [dropbox/pynsot#73]
Because the default view for lists of results is table view, currently most output from `nsot` util is not grep-friendly.

For example, if you want to check the value of an attribute, you have to do something like this:

```
$ nsot devices list -a owner=jathan | egrep 'owner|vendor'
| 26685   foo-bar1   owner=jathan      |
|                    vendor=juniper    |
| 26687   foo-bar2   owner=jathan      |
|                    vendor=cisco      |
```

This, quite frankly, sucks. The ideal solution to this may include having some sort of delimited output, or the ability to filter the desired fields to be displayed. Or maybe this would be something better performed under the `values` command (e.g. `nsot values list [args]`).

**Comment by coxley** [comment]
Or have some fully-qualified format like findutils' `find`

**Comment by jathanism** [comment]
I like it!
