### ISSUE TITLE
Enable update to attributes by natural name via CLI

### ISSUE THREAD

**Issue by coxley** [dropbox/pynsot#83]
Currently it's not possible to update attributes by natural key via CLI:

```bash

$ nsot attributes list -r network -n owner
+-----------------------------------------------------------------------------------------------+
| ID   Name    Resource   Required?   Display?   Multi?   Constraints         Description       |
+-----------------------------------------------------------------------------------------------+
| 54   owner   Network    False       True       False    pattern=            Owner of resource |
|                                                         valid_values=                         |
|                                                         allow_empty=False                     |
+-----------------------------------------------------------------------------------------------+

$ nsot attributes update -r network -n owner -V test
Error: no such option: -r
```

Let's implement this!

**Comment by jathanism** [comment]
That's currently because Attribute isn't a "Resource" type (don't have attributes).

Also, because they would require a compound natural key (resource_name, name) which isn't an easy analog for a pk, it would require more moving parts. 

Definitely doable, just isn't as quick a win as it was with the Resource types.

**Comment by coxley** [comment]
Are you saying it should be implemented client side behind the scenes or a compound natural key added in the backend?

**Comment by jathanism** [comment]
@coxley I don't know yet. It's likely going to be a mix of both?
